### ISSUE TITLE
Add links to the depedencies

### ISSUE THREAD

**Issue by lewismc** [USGS-EROS/espa-product-formatter#14]
Right now it is confusing as to which versions of each of the [dependencies](https://github.com/USGS-EROS/espa-product-formatter#dependencies) is required and also where to download these from.
I think that detailed instructions on how each dependency should be installed is too verbose however locations from where they can be downloaded from would be most helpful.

**Comment by gschmidt-usgs** [comment]
* GCTP libraries (obtained from the GCTP directory in the HDF-EOS2 source code)
  * TIFF libraries (3.8.2 or most current) -- ftp://ftp.remotesensing.org/pub/libtiff/
  * GeoTIFF libraries (1.2.5 or most current) -- ftp://ftp.remotesensing.org/pub/geotiff/libgeotiff/
  * HDF4 libraries (4.2.5 or most current) -- https://www.hdfgroup.org/ftp/HDF/releases/
  * HDF-EOS2 libraries (2.18 or most current) -- ftp://edhs1.gsfc.nasa.gov/edhs/hdfeos/latest_release/
  * JPEG libraries (version 6b) -- http://www.ijg.org/files/
  * ZLIB libraries (version 1.2.8) -- http://zlib.net/
  * XML2 libraries -- http://www.linuxfromscratch.org/blfs/view/svn/general/libxml2.html
  * Land/water static polygon -- http://espa.cr.usgs.gov/downloads/auxiliaries/land_water_poly/land_no_buf.ply.gz

NOTE: The HDF-EOS2 link currently provides the source for the HDF4, JPEG, and ZLIB libraries in addition to the HDF-EOS2 library.

**Comment by lewismc** [comment]
@gschmidt-usgs 
thank you :)
![images](https://cloud.githubusercontent.com/assets/1165719/9398043/a195e9ae-4757-11e5-8a36-0e7f98201036.jpg)
