### ISSUE TITLE
undefined reference to symbol 'deflate'

### ISSUE THREAD

**Issue by wessm** [USGS-EROS/espa-product-formatter#17]
I tried compiling the product formatter on my Ubuntu 14.04 machine. After sorting out various problems with the libraries, `make` nearly finishes successfully until this error appears:

    make all in tools...
    make[1]: Entering directory `/home/h0540427/espa-product-formatter/src/raw_binary/tools'
    gcc -Wall -g -O2 -I. -I../include -I/usr/include/libxml2/libxml -I/usr/include/x86_64-linux-gnu -I/usr/include/geotiff -I/usr/local/hdf4/include -I/home/h0540427/hdfeos/include -I -I -o convert_espa_to_hdf convert_espa_to_hdf.o -L../lib -l_espa_format_conversion -l_espa_raw_binary -l_espa_common -L/usr/lib/x86_64-linux-gnu -lxml2 -L/home/h0540427/hdfeos/hdfeos2/lib -lhdfeos -L/home/h0540427/hdfeos/hdfeos2/lib -lGctp -L/usr/local/hdf4/lib -lmfhdf -ldf -L/usr/lib/x86_64-linux-gnu -ljpeg -L -ljbig -L -lz -lm
    /usr/bin/ld: /usr/lib/x86_64-linux-gnu/libxml2.so: undefined reference to symbol 'deflate'
    //usr/local/lib/libz.so.1: error adding symbols: DSO missing from command line
    collect2: error: ld returned 1 exit status
    make[1]: *** [convert_espa_to_hdf] Error 1
    make[1]: Leaving directory `/home/h0540427/espa-product-formatter/src/raw_binary/tools'
    make: *** [all] Error 2

I really don't know what to do now, can anyone help me?

BR and thank you
Michael

**Comment by gschmidt-usgs** [comment]
We have pushed a new release of the product formatter source code in addition to filling in some missing links in the README file.  Particularly the JBIG library and ZLIB library need to be installed and the associated environment variables need to be defined.  Please take a look at the new README file and see if those environment variables and libraries will solve your build issue.  Sorry for any inconvenience.

**Comment by wessm** [comment]
Thank you very much for your update! It works now!

(The two ZLIB path variables were missing in the readme yesterday, that's why this library wasn't found)
