### ISSUE TITLE
land_no_buf.ply.gz no longer available

### ISSUE THREAD

**Issue by HyperplaneOrg** [USGS-EROS/espa-product-formatter#19]
Any chance this:
http://espa.cr.usgs.gov/downloads/auxiliaries/land_water_poly/land_no_buf.ply.gz
can be posted again?

**Comment by dhill-usgs** [comment]
done.

On Mon, Nov 16, 2015 at 4:24 PM, Andrew Michaelis <notifications@github.com>
wrote:

> Any chance this:
>
> http://espa.cr.usgs.gov/downloads/auxiliaries/land_water_poly/land_no_buf.ply.gz
> can be posted again?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/USGS-EROS/espa-product-formatter/issues/19>.
>



-- 
David V. Hill
LSRD
SGT
Contractor to USGS Earth Resources Observation And Science Center (EROS)
47914 252nd Street
Sioux Falls, SD 57198-9801
605.594.2639
dhill@usgs.gov
