### ISSUE TITLE
hdfeos link not workin

### ISSUE THREAD

**Issue by aafaque33** [USGS-EROS/espa-product-formatter#24]
The link provided in the Readme / Documentation 
http://espa.cr.usgs.gov/downloads/auxiliaries/hdfeos2.19v1.00.tar.Z

It's giving 404 not found error , if it's moved somewhere else please let me know so I can download GTCP Libraries

**Comment by gschmidt-usgs** [comment]
Please pull the file from
http://espa.cr.usgs.gov/downloads/auxiliaries/

   - HDF-EOS2.19v1.00.tar.Z
   <http://espa.cr.usgs.gov/downloads/auxiliaries/HDF-EOS2.19v1.00.tar.Z>


We also understand that the original NASA website is back up and running
and the HDF-EOS2 source code should be available from their website as
well.  The README will be updated to reflect this change.

--------------------------------------------------------------
Gail Schmidt
Software Engineer
Stinger Ghaffarian Technologies (SGT, Inc.)
Contractor to the USGS Earth Resources Observation and Science (EROS) Center
Rapid City, SD  57701
605-593-2722   Phone
605-394-6078   Fax
gschmidt@usgs.gov

Adaptation - "Manage the unavoidable"
Mitigation - "Avoid the unmanageable"
