### ISSUE TITLE
Compile error in  espa-product-formatter/raw_binary/land_water_mask_libs

### ISSUE THREAD

**Issue by chexianghong** [USGS-EROS/espa-product-formatter#45]
Hi,

I follow the instructions to install espa-product-formatter, but after set all the environment of inculde and lib paths. I got an error as follows.

make all in land_water_mask_libs...
make[1]: Entering directory '/home/chexh/ESPA/espa-product-formatter/raw_binary/land_water_mask_libs'
gcc -Wall  -O2    -I. -I../include -I/usr/include/libxml2 -I/usr/include/hdf/ -I -c generate_land_water_mask.c
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
/tmp/ccauGQmO.o: In function `generate_land_water_mask':
generate_land_water_mask.c:(.text+0x408): undefined reference to `ias_geo_shape_mask_projection'
generate_land_water_mask.c:(.text+0x5a3): undefined reference to `error_handler'
generate_land_water_mask.c:(.text+0x631): undefined reference to `deg_to_dms'
generate_land_water_mask.c:(.text+0x649): undefined reference to `deg_to_dms'
generate_land_water_mask.c:(.text+0x6a2): undefined reference to `deg_to_dms'
generate_land_water_mask.c:(.text+0x6ba): undefined reference to `deg_to_dms'
generate_land_water_mask.c:(.text+0x6d2): undefined reference to `deg_to_dms'
generate_land_water_mask.c:(.text+0x74d): undefined reference to `error_handler'
collect2: error: ld returned 1 exit status
Makefile:90: recipe for target 'generate_land_water_mask.o' failed
make[1]: *** [generate_land_water_mask.o] Error 1
make[1]: Leaving directory '/home/chexh/ESPA/espa-product-formatter/raw_binary/land_water_mask_libs'
Makefile:24: recipe for target 'libraries' failed
make: *** [libraries] Error 1

I use the latest version. commit a1731ddb728bead16fbd0e1ced62193e2a42037e.
I think this error is about Makefile, but I could not fix it.
I search a lot but still can't fix it. So please help! Thanks a lot!

Best regards,

Qing

**Comment by gschmidt-usgs** [comment]
It appears your HDFEOS_INC environment variable is not setup.

NOTICE:  This email may contain confidential, proprietary, or competition
sensitive bid or proposal procurement information.  Unauthorized disclosure
of this information may carry criminal penalties as set forth in the
Procurement Integrity Act, 41 U.S.C. 423, as amended.  Further, the
unauthorized disclosure of certain commercial information by civil servants
may result in fines or imprisonment under the Trade Secrets Act (18 U.S.C.
1905).  If you have received this information in error, please delete it,
including all copies, and notify the sender of the error immediately.

**Comment by chexianghong** [comment]
So cool! You are the best! That's my fault. I forgot this HDFEOS_INC settings.
