### ISSUE TITLE
problems with compilation - cannot find -lGctp

### ISSUE THREAD

**Issue by pesekon2** [USGS-EROS/espa-product-formatter#53]
With the following variables, I am always ending with an error `cannot find -lGctp`. Am I doing something wrong?

```
export PREFIX=/tmp/usgs/
export ESPA_LAND_MASS_POLYGON=$PREFIX/static_data/land_no_buf.ply
export HDFEOS_GCTPINC=/usr/include/gctp/
export HDFEOS_GCTPLIB=/usr/lib/x86_64-linux-gnu/
export TIFFINC=/usr/include/x86_64-linux-gnu/
export TIFFLIB=/usr/lib/x86_64-linux-gnu/
export GEOTIFF_INC=/usr/include/geotiff/
export GEOTIFF_LIB=/usr/lib/x86_64-linux-gnu/
export HDFINC=/usr/include/x86_64-linux-gnu/hdf/
export HDFLIB=/usr/lib/
export HDF5INC=/usr/include/hdf5/serial/
export HDF5LIB=/usr/lib/x86_64-linux-gnu/hdf5/
export HDFEOS_INC=/usr/include/hdf/
export HDFEOS_LIB=/usr/lib/x86_64-linux-gnu/
export HDFEOS5_INC=/usr/include/hdf-eos5/
export HDFEOS5_LIB=/usr/lib/x86_64-linux-gnu/
export NCDF4INC=/usr/include/
export NCDF4LIB=/usr/lib/x86_64-linux-gnu/
export JPEGINC=/usr/include/
export JPEGLIB=/usr/lib/x86_64-linux-gnu/
export XML2INC=/usr/include/libxml2/
export XML2LIB=/usr/lib/x86_64-linux-gnu/
export JBIGINC=/usr/include/
export JBIGLIB=/usr/lib/x86_64-linux-gnu/
export ZLIBINC=/usr/include/
export ZLIBLIB=/usr/lib/x86_64-linux-gnu/
export CURLINC=/usr/include/x86_64-linux-gnu/curl/
export CURLLIB=/usr/lib/x86_64-linux-gnu/
export LZMAINC=/usr/include/lzma/
export LZMALIB=/usr/lib/x86_64-linux-gnu/
export IDNINC=/usr/include/
export IDNLIB=/usr/lib/x86_64-linux-gnu/
export ESPAINC=/home/ondrej/Downloads/espa-product-formatter/raw_binary/include/
export ESPALIB=/home/ondrej/Downloads/espa-product-formatter/raw_binary/lib/
```

This is the error I am getting during make:

```
gcc -Wall  -O2    -I. -I../include -I/usr/include/libxml2/ -I/usr/include/x86_64-linux-gnu/ -I/usr/include/geotiff/ -I/usr/include/x86_64-linux-gnu/hdf/ -I/usr/include/hdf/ -I/usr/include/ -I/usr/include/ -o convert_lpgs_to_espa convert_lpgs_to_espa.o -L../lib -l_espa_format_conversion -l_espa_raw_binary -l_espa_common -L/usr/lib/x86_64-linux-gnu/ -lxml2 -L/usr/lib/x86_64-linux-gnu/ -ltiff -L/usr/lib/x86_64-linux-gnu/ -lgeotiff -L/usr/lib/x86_64-linux-gnu/ -lGctp -L/usr/lib/x86_64-linux-gnu/ -ljpeg -L/usr/lib/x86_64-linux-gnu/ -ljbig -L/usr/lib/x86_64-linux-gnu/ -lz -L/usr/lib/x86_64-linux-gnu/ -llzma -lm
/usr/bin/ld: cannot find -lGctp
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:276: convert_lpgs_to_espa] Error 1
make[1]: Leaving directory '/home/ondrej/Downloads/espa-product-formatter/raw_binary/tools'
make: *** [Makefile:31: executables] Error 1
```

In `/usr/lib/x86_64-linux-gnu/`, I have besides others also these files `libgctp-2.0.0.so  libgctp.a         libgctp.so        libgctp.so.2.0.0`

**Comment by gschmidt-usgs** [comment]
I show the following in my HDFEOS_GCTPLIB directory.  Do you have the libGctp.a file in your HDFEOS_GCTPLIB directory?

libGctp.a  libGctp.la  libhdfeos.a  libhdfeos.la
-------------------------------------------------------------------------------------------------------
Gail Schmidt
Software Engineer | Technical Support Services Contract (TSSC)
KBR Contractor to the USGS Earth Resources Observation and Science (EROS) Center
Web: https://www.usgs.gov/centers/eros

**Comment by pesekon2** [comment]
That could be the problem - in the `HDFEOS_GCTPLIB` I do not have `libGctp.a` and neither `libGctp.la`. I have there only `libhdfeos.a         libhdfeos.so        libhdfeos.so.0      libhdfeos.so.0.0.0 libgctp-2.0.0.so  libgctp.a         libgctp.so        libgctp.so.2.0.0`. I haven't found `libGctp.a` with the capital `G` nor `libGctp.la` anywhere in my `/usr/`. 

Do I have to build `hdfeos` from source? I have installed `libhdfeos-dev`, `libhdfeos0`, `libhe5-hdfeos-dev` and `libhe5-hdfeos0` through `apt`. I am using Debian 10.

**Comment by gschmidt-usgs** [comment]
You can try using the libgctp.a library (-lgctp) instead of the libGctp.a (-lGctp)

-gail
-------------------------------------------------------------------------------------------------------
Gail Schmidt
Software Engineer | Technical Support Services Contract (TSSC)
KBR Contractor to the USGS Earth Resources Observation and Science (EROS) Center
Web: https://www.usgs.gov/centers/eros

**Comment by pesekon2** [comment]
Changing `-lGctp` to `-lgctp` everywhere in `raw_binary/Makefile` solved the issue. Thank you. 

(maybe putting this trick as a note in the README, if I'm not the only one facing this problem?)
